"""
Cardiology Specialist Agent - Board-certified cardiologist for cardiovascular assessment
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add src to path for relative imports
src_path = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(src_path))
from typing import Any, Optional
from google.genai import types
from google.adk.models.google_llm import Gemini
from google.adk import Agent, Runner
from google.adk.agents import SequentialAgent
from google.adk.tools import google_search, url_context, AgentTool, BaseTool
from google.adk.tools.tool_context import ToolContext
from patientmap.common.config import AgentConfig
from patientmap.tools.research_tools import google_scholar_tool, pubmed_tool, semantic_scholar_tool, wikipedia_tool
from patientmap.common.helper_functions import retry_config, handle_tool_error


# Load configuration
config_path = Path(__file__).parent.parent.parent.parent.parent.parent / ".profiles" / "clinical" / "cardiology_agent.yaml"

try:
    config = AgentConfig(str(config_path)).get_agent()
    cardiology_settings = config
except (FileNotFoundError) as e:
    raise FileNotFoundError(f"Configuration file not found at {config_path}") from e
finally:
    # Clean up sys.path
    sys.path.pop(0)


check_agent = Agent(
    name="cardiology_specialist_check_agent",
    description="Validates and checks the responses generated by the Cardiology Specialist Agent for accuracy and completeness.",
    model=Gemini(model_name=cardiology_settings.model, retry_options=retry_config),
    instruction="You are a cardiology expert. Your task is to validate the responses provided by the Cardiology Specialist Agent. Ensure that all information is accurate, relevant, and complete. If any information is missing or incorrect, provide the necessary corrections or additions. You must use your tools to verify information. If a tool returns an error message, acknowledge it and continue with the validation based on available information.",
    tools=[google_search, url_context],
    on_tool_error_callback=handle_tool_error,
)

# Create agent
cardiology_agent = Agent(
    name=cardiology_settings.agent_name,
    description=cardiology_settings.description,
    model=Gemini(model_name=cardiology_settings.model, retry_options=retry_config),
    instruction=cardiology_settings.instruction,
    tools=[pubmed_tool(), google_scholar_tool(), semantic_scholar_tool(), wikipedia_tool(), AgentTool(check_agent)],
    on_tool_error_callback=handle_tool_error,
)


if __name__ == "__main__":
    print(cardiology_agent)